#include <bgfx/bgfx.h>

#include <catch2/catch_test_macros.hpp>
#include <cstdio>
#include <string>

#include "engine/ui/IFont.h"
#include "engine/ui/MsdfFont.h"

// ---------------------------------------------------------------------------
// TestMsdfFont
//
// Exercises the MSDF font backend. Because shader programs and GPU textures
// can only be created when bgfx has been initialised with a non-Noop backend,
// most of the assertions here are restricted to CPU-side state: JSON parsing,
// glyph lookup, kerning, line metrics, and the FontRenderer enum.
//
// If the default MSDF atlas asset is not present on disk, the test is
// skipped (via an early return + SUCCEED) rather than failing, because the
// asset is generated by an external CLI tool (msdf-atlas-gen) that is not
// guaranteed to be available in every build environment.
// ---------------------------------------------------------------------------

namespace
{

const char* kMetricsPath =
    ENGINE_SOURCE_DIR "/assets/fonts/default/JetBrainsMono-Regular-msdf.json";
const char* kAtlasPath = ENGINE_SOURCE_DIR "/assets/fonts/default/JetBrainsMono-Regular-msdf.png";

bool fileExists(const char* path)
{
    std::FILE* f = std::fopen(path, "rb");
    if (!f)
        return false;
    std::fclose(f);
    return true;
}

}  // namespace

TEST_CASE("MsdfFont identifies as the MSDF backend", "[ui][msdf]")
{
    engine::ui::MsdfFont font;
    REQUIRE(font.renderer() == engine::ui::FontRenderer::Msdf);
}

TEST_CASE("MsdfFont returns nullptr for missing glyphs", "[ui][msdf]")
{
    engine::ui::MsdfFont font;
    // Uninitialised font — every lookup must miss.
    REQUIRE(font.getGlyph(65) == nullptr);
    REQUIRE(font.getKerning(65, 86) == 0.f);
    REQUIRE(font.lineHeight() == 0.f);
}

TEST_CASE("MsdfFont loads a real atlas when available", "[ui][msdf]")
{
    if (!fileExists(kMetricsPath) || !fileExists(kAtlasPath))
    {
        // Asset not generated in this checkout — skip. msdf-atlas-gen is
        // documented in assets/fonts/default/README.md.
        SUCCEED("Default MSDF atlas not present; skipping real-load assertions");
        return;
    }

    engine::ui::MsdfFont font;
    REQUIRE(font.loadFromFile(kMetricsPath, kAtlasPath));

    REQUIRE(font.glyphCount() > 0);
    REQUIRE(font.lineHeight() > 0.f);
    REQUIRE(font.nominalSize() > 0.f);
    REQUIRE(font.distanceRange() > 0.f);

    // 'A' (U+0041) is guaranteed to be in the ASCII charset msdf-atlas-gen
    // emits when called with `-charset ascii`.
    const engine::ui::GlyphMetrics* a = font.getGlyph('A');
    REQUIRE(a != nullptr);
    REQUIRE(a->advance > 0.f);

    // Only assert on GPU handles if bgfx was initialised with a real backend.
    if (bgfx::getRendererType() != bgfx::RendererType::Noop)
    {
        REQUIRE(bgfx::isValid(font.atlasTexture()));
        REQUIRE(bgfx::isValid(font.program()));
    }
}
