#include <bgfx/bgfx.h>

#include <catch2/catch_test_macros.hpp>
#include <cmath>

#include "engine/rendering/RenderSettings.h"
#include "engine/rendering/Renderer.h"
#include "engine/rendering/ShaderUniforms.h"
#include "engine/rendering/systems/SsaoSystem.h"

// ---------------------------------------------------------------------------
// Shared headless bgfx fixture
// ---------------------------------------------------------------------------

struct HeadlessBgfx
{
    engine::rendering::Renderer renderer;

    HeadlessBgfx()
    {
        engine::rendering::RendererDesc desc{};
        desc.headless = true;
        desc.width = 1;
        desc.height = 1;
        REQUIRE(renderer.init(desc));
    }

    ~HeadlessBgfx()
    {
        renderer.shutdown();
    }

    HeadlessBgfx(const HeadlessBgfx&) = delete;
    HeadlessBgfx& operator=(const HeadlessBgfx&) = delete;
};

// ---------------------------------------------------------------------------
// SsaoSystem: init does not crash in headless mode
// ---------------------------------------------------------------------------

TEST_CASE("SsaoSystem: init does not crash in headless mode", "[ssao]")
{
    HeadlessBgfx bgfxCtx;

    engine::rendering::SsaoSystem ssao;
    REQUIRE_NOTHROW(ssao.init(1280, 720));
    REQUIRE_NOTHROW(ssao.shutdown());
}

// ---------------------------------------------------------------------------
// SsaoSystem: ssaoMap returns BGFX_INVALID_HANDLE after shutdown
// ---------------------------------------------------------------------------

TEST_CASE("SsaoSystem: ssaoMap returns BGFX_INVALID_HANDLE after shutdown", "[ssao]")
{
    HeadlessBgfx bgfxCtx;

    engine::rendering::SsaoSystem ssao;
    ssao.init(1280, 720);

    // After shutdown the handle must be invalid (all GPU resources freed).
    ssao.shutdown();
    REQUIRE(!bgfx::isValid(ssao.ssaoMap()));
}

// ---------------------------------------------------------------------------
// SsaoSystem: submit does not crash in headless mode
// ---------------------------------------------------------------------------

TEST_CASE("SsaoSystem: submit does not crash in headless mode", "[ssao]")
{
    HeadlessBgfx bgfxCtx;

    engine::rendering::SsaoSystem ssao;
    ssao.init(1280, 720);

    engine::rendering::ShaderUniforms uniforms{};
    uniforms.init();

    engine::rendering::SsaoSettings settings;

    bgfxCtx.renderer.beginFrame();
    // Pass BGFX_INVALID_HANDLE for depthTex and fsTriVb — headless mode should
    // handle this gracefully (submit() guards with isValid checks).
    REQUIRE_NOTHROW(ssao.submit(settings, uniforms, BGFX_INVALID_HANDLE,
                                engine::rendering::kViewPostProcessBase, BGFX_INVALID_HANDLE));
    bgfxCtx.renderer.endFrame();

    uniforms.destroy();
    ssao.shutdown();
}

// ---------------------------------------------------------------------------
// SSAO kernel: 16 samples have unit-hemisphere distribution
//
// Verifies the kernel generated by SsaoSystem::init():
//   - exactly 16 samples
//   - all z > 0  (samples lie on the positive hemisphere)
//   - all lengths in (0, 1]
// ---------------------------------------------------------------------------

TEST_CASE("SSAO kernel: 16 samples have unit-hemisphere distribution", "[ssao]")
{
    // We can inspect the kernel without a GPU — run a standalone copy of the
    // same deterministic LCG used in SsaoSystem::init().
    // Fixed seed = 42 (matches SsaoSystem.cpp).

    auto lcgRand = [](uint32_t& state) -> float
    {
        state = state * 1664525u + 1013904223u;
        return static_cast<float>(state >> 8) / static_cast<float>(1u << 24);
    };

    constexpr int kSamples = 16;
    float kernel[kSamples][4]{};

    uint32_t rngState = 42u;
    for (int i = 0; i < kSamples; ++i)
    {
        float x = lcgRand(rngState) * 2.0f - 1.0f;
        float y = lcgRand(rngState) * 2.0f - 1.0f;
        float z = lcgRand(rngState);  // [0, 1)

        float len = std::sqrt(x * x + y * y + z * z);
        if (len < 1e-6f)
            len = 1e-6f;
        x /= len;
        y /= len;
        z /= len;

        float scale = static_cast<float>(i) / static_cast<float>(kSamples);
        scale = 0.1f + scale * scale * 0.9f;

        kernel[i][0] = x * scale;
        kernel[i][1] = y * scale;
        kernel[i][2] = z * scale;
        kernel[i][3] = 0.0f;
    }

    for (int i = 0; i < kSamples; ++i)
    {
        float x = kernel[i][0];
        float y = kernel[i][1];
        float z = kernel[i][2];

        float length = std::sqrt(x * x + y * y + z * z);

        // All samples must lie on the positive hemisphere (z component > 0).
        // Because the direction is normalised and then scaled, the unit
        // direction's z component is positive; the scaled version preserves sign.
        REQUIRE(z > 0.0f);

        // Length must be in (0, 1].
        REQUIRE(length > 0.0f);
        REQUIRE(length <= 1.0f + 1e-5f);  // small epsilon for float rounding
    }
}
