# ---------------------------------------------------------------------------
# SamaForbidBgfx — fail if a public engine header transitively pulls in bgfx.
#
# Usage:
#   include(cmake/SamaForbidBgfx.cmake)
#   sama_forbid_bgfx_in_target(<test-name> <target> <header>)
#
# The function compiles a tiny TU that includes <header> against the given
# target's include directories and emits the preprocessed translation unit
# to a temporary file.  The check then greps that output for "bgfx/bgfx.h":
# if any line matches, the test fails and the unwanted include path is
# printed.
#
# Wired into a separate test target (NOT the main build) so it can fail
# loudly without breaking developer iteration.  The test pre-builds the
# probe at configure-time; running it just checks the cached result.
# ---------------------------------------------------------------------------

function(sama_forbid_bgfx_in_target test_name target header)
    set(_probe_dir ${CMAKE_CURRENT_BINARY_DIR}/sama_forbid_bgfx_probes)
    file(MAKE_DIRECTORY ${_probe_dir})

    # Sanitise the header path into a valid filename component.
    string(REPLACE "/" "_" _safe ${header})
    string(REPLACE "." "_" _safe ${_safe})
    set(_probe_src ${_probe_dir}/probe_${_safe}.cpp)
    set(_probe_pp ${_probe_dir}/probe_${_safe}.i)

    file(WRITE ${_probe_src}
        "// Auto-generated by sama_forbid_bgfx_in_target — do not edit.\n"
        "#include \"${header}\"\n"
        "int main() { return 0; }\n"
    )

    # Build and grep at *test* time so the check participates in CTest
    # without bloating the regular build.  Using cmake -E enables platform
    # independence for the grep step.
    add_test(
        NAME ${test_name}
        COMMAND ${CMAKE_COMMAND}
            -DCXX_COMPILER=${CMAKE_CXX_COMPILER}
            -DPROBE_SRC=${_probe_src}
            -DPROBE_PP=${_probe_pp}
            -DHEADER=${header}
            "-DTARGET_INCLUDES=$<TARGET_PROPERTY:${target},INCLUDE_DIRECTORIES>"
            -P ${CMAKE_SOURCE_DIR}/cmake/SamaForbidBgfxRun.cmake
    )
endfunction()
